// UI label translations for all 14 languages.
import type { LangCode } from "./multiLangDict";

export const UI_DICT: Record<string, Partial<Record<LangCode, string>>> = {
  "URCOOKED BOOK": { /* same in all */ },
  "Enter your 4-digit PIN": {
    bis: "Ibutang ang imong 4-digit PIN", tg: "Ilagay ang iyong 4-digit na PIN",
    zh: "输入4位PIN码", ko: "4자리 PIN 입력", hi: "4-अंकीय PIN दर्ज करें",
    vi: "Nhập mã PIN 4 số", tw: "輸入4位PIN碼", th: "ใส่รหัส PIN 4 หลัก",
    hk: "輸入4位PIN碼", sg: "Masukkan PIN 4 digit", it: "Inserisci il PIN di 4 cifre",
    fr: "Entrez votre code PIN à 4 chiffres", yo: "Te PIN nọmbà 4",
  },
  "Change PIN": {
    bis: "Usba ang PIN", tg: "Palitan ang PIN",
    zh: "更改PIN", ko: "PIN 변경", hi: "PIN बदलें",
    vi: "Đổi PIN", tw: "更改PIN碼", th: "เปลี่ยน PIN",
    hk: "更改PIN碼", sg: "Tukar PIN", it: "Cambia PIN",
    fr: "Changer le PIN", yo: "Yí PIN padà",
  },
  "Enter new PIN": {
    bis: "Ibutang ang bag-ong PIN", tg: "Ilagay ang bagong PIN",
    zh: "输入新PIN", ko: "새 PIN 입력", hi: "नया PIN दर्ज करें",
    vi: "Nhập PIN mới", tw: "輸入新PIN碼", th: "ใส่ PIN ใหม่",
    hk: "輸入新PIN碼", sg: "Masukkan PIN baru", it: "Inserisci nuovo PIN",
    fr: "Entrez nouveau PIN", yo: "Te PIN tuntun",
  },
  "Confirm new PIN": {
    bis: "Kumpirma ang bag-ong PIN", tg: "Kumpirmahin ang bagong PIN",
    zh: "确认新PIN", ko: "새 PIN 확인", hi: "नया PIN कन्फर्म करें",
    vi: "Xác nhận PIN mới", tw: "確認新PIN碼", th: "ยืนยัน PIN ใหม่",
    hk: "確認新PIN碼", sg: "Sahkan PIN baru", it: "Conferma nuovo PIN",
    fr: "Confirmer nouveau PIN", yo: "Ẹ́rí PIN tuntun",
  },
  "Save": { bis: "I-save", tg: "I-save", zh: "保存", ko: "저장", hi: "सहेजें", vi: "Lưu", tw: "儲存", th: "บันทึก", hk: "儲存", sg: "Simpan", it: "Salva", fr: "Enregistrer", yo: "Pàṣẹ" },
  "Cancel": { bis: "Kanselahon", tg: "Kanselahin", zh: "取消", ko: "취소", hi: "रद्द", vi: "Hủy", tw: "取消", th: "ยกเลิก", hk: "取消", sg: "Batal", it: "Annulla", fr: "Annuler", yo: "Fagile" },
  "New Recipe": { bis: "Bag-ong Resipe", tg: "Bagong Resipe", zh: "新食谱", ko: "새 레시피", hi: "नयी रेसिपी", vi: "Công thức mới", tw: "新食譜", th: "สูตรใหม่", hk: "新食譜", sg: "Resipi Baru", it: "Nuova Ricetta", fr: "Nouvelle Recette", yo: "Àwọn èròjà tuntun" },
  "Export Book": { bis: "I-export ang Libro", tg: "I-export ang Libro", zh: "导出食谱书", ko: "책 내보내기", hi: "पुस्तक निर्यात", vi: "Xuất sách", tw: "匯出食譜書", th: "ส่งออกหนังสือ", hk: "匯出食譜書", sg: "Eksport Buku", it: "Esporta Libro", fr: "Exporter le Livre", yo: "Gbe àwọn àwọn èròjà jáde" },
  "Import Book": { bis: "I-import ang Libro", tg: "I-import ang Libro", zh: "导入食谱书", ko: "책 가져오기", hi: "पुस्तक आयात", vi: "Nhập sách", tw: "匯入食譜書", th: "นำเข้าหนังสือ", hk: "匯入食譜書", sg: "Import Buku", it: "Importa Libro", fr: "Importer le Livre", yo: "Gbe àwọn àwọn èròjà wá" },
  "Create Recipe": { bis: "Paghimo og Resipe", tg: "Gumawa ng Resipe", zh: "创建食谱", ko: "레시피 만들기", hi: "रेसिपी बनाएं", vi: "Tạo công thức", tw: "建立食譜", th: "สร้างสูตร", hk: "建立食譜", sg: "Buat Resipi", it: "Crea Ricetta", fr: "Créer une Recette", yo: "Ṣ'àwọn èròjà" },
  "Manual Builder": { bis: "Manwal nga Builder", tg: "Manwal na Builder", zh: "手动构建", ko: "수동 빌더", hi: "मैनुअल बिल्डर", vi: "Trình xây dựng thủ công", tw: "手動建立", th: "ตัวสร้างด้วยมือ", hk: "手動建立", sg: "Pembina Manual", it: "Costruttore Manuale", fr: "Constructeur Manuel", yo: "Olùṣẹ̀dá ọwọ́" },
  "AI Smart Importer": { bis: "AI Smart Importer", tg: "AI Smart Importer", zh: "AI智能导入", ko: "AI 스마트 가져오기", hi: "AI स्मार्ट आयात", vi: "Nhập thông minh AI", tw: "AI智慧匯入", th: "AI นำเข้าอัจฉริยะ", hk: "AI智能匯入", sg: "Pengimport Pintar AI", it: "Importatore Intelligente AI", fr: "Importateur Intelligent IA", yo: "Onígbéwọle AI" },
  "Recipe Title": { bis: "Titulo sa Resipe", tg: "Pamagat ng Resipe", zh: "食谱标题", ko: "레시피 제목", hi: "रेसिपी शीर्षक", vi: "Tên công thức", tw: "食譜標題", th: "ชื่อสูตร", hk: "食譜標題", sg: "Tajuk Resipi", it: "Titolo Ricetta", fr: "Titre de la Recette", yo: "Oríkì Àwọn èròjà" },
  "Description": { bis: "Pagdul-ong", tg: "Paglalarawan", zh: "描述", ko: "설명", hi: "विवरण", vi: "Mô tả", tw: "描述", th: "คำอธิบาย", hk: "描述", sg: "Penerangan", it: "Descrizione", fr: "Description", yo: "Àpèjúwe" },
  "Servings": { bis: "Serbisyu", tg: "Porsyon", zh: "份量", ko: "인분", hi: "सर्विंग", vi: "Phần ăn", tw: "份量", th: "เสิร์ฟ", hk: "份量", sg: "Sajian", it: "Porzioni", fr: "Portions", yo: "Ìpín" },
  "Ingredients": { bis: "Sangkap", tg: "Sangkap", zh: "食材", ko: "재료", hi: "सामग्री", vi: "Nguyên liệu", tw: "食材", th: "วัตถุดิบ", hk: "食材", sg: "Bahan-bahan", it: "Ingredienti", fr: "Ingrédients", yo: "Èròjà" },
  "Directions": { bis: "Mga Lakang", tg: "Mga Hakbang", zh: "步骤", ko: "조리순서", hi: "निर्देश", vi: "Cách làm", tw: "步驟", th: "ขั้นตอน", hk: "步驟", sg: "Arahan", it: "Istruzioni", fr: "Instructions", yo: "Àwọn ìgbésẹ̀" },
  "Add Row": { bis: "Dugang Row", tg: "Dagdag Row", zh: "添加行", ko: "행 추가", hi: "पंक्ति जोड़ें", vi: "Thêm dòng", tw: "新增行", th: "เพิ่มแถว", hk: "加行", sg: "Tambah Baris", it: "Aggiungi Riga", fr: "Ajouter Ligne", yo: "Fifi Rọ́ọ̀" },
  "Add Step": { bis: "Dugang Lakang", tg: "Dagdag Hakbang", zh: "添加步骤", ko: "단계 추가", hi: "चरण जोड़ें", vi: "Thêm bước", tw: "新增步驟", th: "เพิ่มขั้นตอน", hk: "加步驟", sg: "Tambah Langkah", it: "Aggiungi Passo", fr: "Ajouter Étape", yo: "Fifi Ìgbésẹ̀" },
  "Heat": { bis: "Kainit", tg: "Apoy", zh: "火候", ko: "불", hi: "आंच", vi: "Lửa", tw: "火候", th: "ไฟ", hk: "火候", sg: "Api", it: "Fuoco", fr: "Chaleur", yo: "Iná" },
  "Timer": { bis: "Timer", tg: "Timer", zh: "计时器", ko: "타이머", hi: "टाइमर", vi: "Hẹn giờ", tw: "計時器", th: "ตัวจับเวลา", hk: "計時器", sg: "Pemasa", it: "Timer", fr: "Minuteur", yo: "Àkókò" },
  "Save to Book": { bis: "I-save sa Libro", tg: "I-save sa Libro", zh: "保存到书", ko: "책에 저장", hi: "पुस्तक में सहेजें", vi: "Lưu vào sách", tw: "儲存到食譜書", th: "บันทึกลงหนังสือ", hk: "儲存到食譜書", sg: "Simpan ke Buku", it: "Salva nel Libro", fr: "Sauvegarder dans le Livre", yo: "Pàṣẹ sínú Ìwé" },
  "Paste Raw Recipe Text": { bis: "I-paste ang Hilaw nga Resipe Text", tg: "I-paste ang Hilaw na Resipe Text", zh: "粘贴原始食谱文本", ko: "레시피 텍스트 붙여넣기", hi: "कच्ची रेसिपी टेक्स्ट पेस्ट करें", vi: "Dán văn bản công thức", tw: "貼上原始食譜文字", th: "วางข้อความสูตร", hk: "貼上原始食譜文字", sg: "Tampal Teks Resipi Mentah", it: "Incolla Testo Ricetta Grezzo", fr: "Coller le Texte de la Recette", yo: "Ẹ́kọ́ Tẹ̀kstì Àwọn èròjà" },
  "Analyze & Format": { bis: "Analisa & I-format", tg: "Suri at I-format", zh: "分析并格式化", ko: "분석 및 포맷", hi: "विश्लेषण और प्रारूप", vi: "Phân tích & Định dạng", tw: "分析並格式化", th: "วิเคราะห์และจัดรูปแบบ", hk: "分析並格式化", sg: "Analisis & Format", it: "Analizza e Formatta", fr: "Analyser et Formater", yo: "Yíwò àti Ṣ'ètò" },
  "Start Cooking": { bis: "Pagsugod sa Pagluto", tg: "Magsimulang Magluto", zh: "开始烹饪", ko: "요리 시작", hi: "खाना बनाना शुरू", vi: "Bắt đầu nấu", tw: "開始烹飪", th: "เริ่มทำอาหาร", hk: "開始烹飪", sg: "Mula Memasak", it: "Inizia a Cucinare", fr: "Commencer à Cuisiner", yo: "Bẹ̀rẹ̀ Síṣe Oúnjẹ" },
  "Total Time": { bis: "Tibook nga Oras", tg: "Kabuuang Oras", zh: "总时间", ko: "총 시간", hi: "कुल समय", vi: "Tổng thời gian", tw: "總時間", th: "เวลาทั้งหมด", hk: "總時間", sg: "Jumlah Masa", it: "Tempo Totale", fr: "Temps Total", yo: "Àkókò Kíkún" },
  "Steps Overview": { bis: "Overview sa mga Lakang", tg: "Pangkalahatang-ideya ng mga Hakbang", zh: "步骤概览", ko: "단계 개요", hi: "चरण अवलोकन", vi: "Tổng quan bước", tw: "步驟概覽", th: "ภาพรวมขั้นตอน", hk: "步驟概覽", sg: "Gambaran Langkah", it: "Panoramica Passi", fr: "Aperçu des Étapes", yo: "Àkójọ Ìgbésẹ̀" },
  "Cook": { bis: "Lutoa", tg: "Lutuin", zh: "烹饪", ko: "요리", hi: "पकाना", vi: "Nấu", tw: "煮", th: "ทำ", hk: "煮", sg: "Masak", it: "Cucina", fr: "Cuisiner", yo: "Ṣe" },
  "View": { bis: "Tan-awa", tg: "Tingnan", zh: "查看", ko: "보기", hi: "देखें", vi: "Xem", tw: "查看", th: "ดู", hk: "查看", sg: "Lihat", it: "Visualizza", fr: "Voir", yo: "Wo" },
  "Back": { bis: "Balik", tg: "Bumalik", zh: "返回", ko: "뒤로", hi: "वापस", vi: "Quay lại", tw: "返回", th: "กลับ", hk: "返回", sg: "Kembali", it: "Indietro", fr: "Retour", yo: "Páàrọ̀" },
  "Exit": { bis: "Gawas", tg: "Lumabas", zh: "退出", ko: "종료", hi: "बाहर", vi: "Thoát", tw: "退出", th: "ออก", hk: "退出", sg: "Keluar", it: "Esci", fr: "Sortir", yo: "Jáde" },
  "Sunod": { bis: "Sunod", tg: "Susunod", zh: "下一步", ko: "다음", hi: "अगला", vi: "Tiếp", tw: "下一步", th: "ถัดไป", hk: "下一步", sg: "Seterusnya", it: "Avanti", fr: "Suivant", yo: "Tẹ̀síwájú" },
  "Balik": { bis: "Balik", tg: "Bumalik", zh: "上一步", ko: "이전", hi: "पिछला", vi: "Lùi", tw: "上一步", th: "ก่อนหน้า", hk: "上一步", sg: "Sebelumnya", it: "Indietro", fr: "Précédent", yo: "Páàrọ̀" },
  "Ingredients for this step (tap to check off)": {
    bis: "Sangkap alang niining lakanga (i-tap aron ma-check)",
    tg: "Sangkap para sa hakbang na ito (i-tap para i-check)",
    zh: "此步骤的食材（点击勾选）", ko: "이 단계의 재료 (탭하여 체크)",
    hi: "इस चरण के लिए सामग्री (चेक करने के लिए टैप करें)",
    vi: "Nguyên liệu cho bước này (chạm để đánh dấu)",
    tw: "此步驟的食材（點擊勾選）", th: "วัตถุดิบสำหรับขั้นตอนนี้ (แตะเพื่อทำเครื่องหมาย)",
    hk: "此步驟的食材（點擊勾選）", sg: "Bahan untuk langkah ini (ketuk untuk tandakan)",
    it: "Ingredienti per questo passo (tocca per spuntare)",
    fr: "Ingrédients pour cette étape (touchez pour cocher)",
    yo: "Èròjà fún ìgbésẹ̀ yìí (tẹ láti ṣ'àmì)",
  },
  "Start Timer": { bis: "Pagsugod sa Timer", tg: "Simulan ang Timer", zh: "开始计时", ko: "타이머 시작", hi: "टाइमर शुरू", vi: "Bắt đầu hẹn giờ", tw: "開始計時", th: "เริ่มจับเวลา", hk: "開始計時", sg: "Mula Pemasa", it: "Avvia Timer", fr: "Démarrer le Minuteur", yo: "Bẹ̀rẹ̀ Àkókò" },
  "Stop Timer": { bis: "Undanga ang Timer", tg: "Itigil ang Timer", zh: "停止计时", ko: "타이머 정지", hi: "टाइमर रोकें", vi: "Dừng hẹn giờ", tw: "停止計時", th: "หยุดจับเวลา", hk: "停止計時", sg: "Hentikan Pemasa", it: "Ferma Timer", fr: "Arrêter le Minuteur", yo: "Dá Àkókò Dúró" },
  "Timer complete!": { bis: "Tapos na ang timer!", tg: "Tapos na ang timer!", zh: "计时完成！", ko: "타이머 완료!", hi: "टाइमर पूर्ण!", vi: "Hết giờ!", tw: "計時完成！", th: "หมดเวลา!", hk: "計時完成！", sg: "Masa tamat!", it: "Timer completo!", fr: "Minuteur terminé!", yo: "Àkókò parí!" },
  "Pro Tip": { bis: "Pro Tip", tg: "Pro Tip", zh: "专业提示", ko: "프로 팁", hi: "प्रो टिप", vi: "Mẹo chuyên gia", tw: "專業提示", th: "เคล็ดลับ", hk: "專業提示", sg: "Tip Pro", it: "Suggerimento Pro", fr: "Astuce Pro", yo: "Ìmọ̀ràn" },
  "Mute": { bis: "Pahilum", tg: "Tahimik", zh: "静音", ko: "음소거", hi: "मौन", vi: "Tắt tiếng", tw: "靜音", th: "ปิดเสียง", hk: "靜音", sg: "Bisu", it: "Muto", fr: "Muet", yo: "Dá ohù dọ́ọ́" },
  "Unmute": { bis: "Pagsulti", tg: "Tumunog", zh: "取消静音", ko: "음소거 해제", hi: "अनम्यूट", vi: "Bật tiếng", tw: "取消靜音", th: "เปิดเสียง", hk: "取消靜音", sg: "Nyahbisu", it: "Riattiva", fr: "Réactiver", yo: "Má dá ohù dọ́ọ́" },
  "Add Photo": { bis: "Dugang Photo", tg: "Magdagdag ng Litrato", zh: "添加照片", ko: "사진 추가", hi: "फोटो जोड़ें", vi: "Thêm ảnh", tw: "新增照片", th: "เพิ่มรูป", hk: "新增照片", sg: "Tambah Foto", it: "Aggiungi Foto", fr: "Ajouter Photo", yo: "Fifi Fóto" },
  "Change Photo": { bis: "Usba ang Photo", tg: "Palitan ang Litrato", zh: "更换照片", ko: "사진 변경", hi: "फोटो बदलें", vi: "Đổi ảnh", tw: "更換照片", th: "เปลี่ยนรูป", hk: "更換照片", sg: "Tukar Foto", it: "Cambia Foto", fr: "Changer Photo", yo: "Yí Fóto padà" },
  "Remove Photo": { bis: "Kuhaa ang Photo", tg: "Alisin ang Litrato", zh: "移除照片", ko: "사진 제거", hi: "फोटो हटाएं", vi: "Xóa ảnh", tw: "移除照片", th: "ลบรูป", hk: "移除照片", sg: "Buang Foto", it: "Rimuovi Foto", fr: "Supprimer Photo", yo: "Yọ Fóto kúrò" },
  "Set Wallpaper": { bis: "Ibutang ang Wallpaper", tg: "Itakda ang Wallpaper", zh: "设置壁纸", ko: "배경화면 설정", hi: "वॉलपेपर सेट करें", vi: "Đặt hình nền", tw: "設定桌布", th: "ตั้งวอลเปเปอร์", hk: "設定桌布", sg: "Tetapkan Kertas Dinding", it: "Imposta Sfondo", fr: "Définir Fond d'écran", yo: "Ṣ'ètò Àwòrán Ìbẹ̀rẹ̀" },
  "Remove Wallpaper": { bis: "Kuhaa ang Wallpaper", tg: "Alisin ang Wallpaper", zh: "移除壁纸", ko: "배경화면 제거", hi: "वॉलपेपर हटाएं", vi: "Xóa hình nền", tw: "移除桌布", th: "ลบวอลเปเปอร์", hk: "移除桌布", sg: "Buang Kertas Dinding", it: "Rimuovi Sfondo", fr: "Supprimer Fond d'écran", yo: "Yọ Àwòrán Ìbẹ̀rẹ̀ kúrò" },
  "Lock Recipe": { bis: "Selda ang Resipe", tg: "I-lock ang Resipe", zh: "锁定食谱", ko: "레시피 잠금", hi: "रेसिपी लॉक", vi: "Khóa công thức", tw: "鎖定食譜", th: "ล็อคสูตร", hk: "鎖定食譜", sg: "Kunci Resipi", it: "Blocca Ricetta", fr: "Verrouiller Recette", yo: "Pa Àwọn èròjà" },
  "Unlock Recipe": { bis: "Ablihi ang Resipe", tg: "I-unlock ang Resipe", zh: "解锁食谱", ko: "레시피 잠금해제", hi: "रेसिपी अनलॉक", vi: "Mở khóa công thức", tw: "解鎖食譜", th: "ปลดล็อคสูตร", hk: "解鎖食譜", sg: "Buka Kunci Resipi", it: "Sblocca Ricetta", fr: "Déverrouiller Recette", yo: "Ṣí Àwọn èròjà padà" },
  "This recipe is locked": { bis: "Kini nga resipe naka-selda", tg: "Naka-lock ang resipeng ito", zh: "此食谱已锁定", ko: "이 레시피는 잠겨있습니다", hi: "यह रेसिपी लॉक है", vi: "Công thức này đã khóa", tw: "此食譜已鎖定", th: "สูตรนี้ถูกล็อค", hk: "此食譜已鎖定", sg: "Resipi ini dikunci", it: "Questa ricetta è bloccata", fr: "Cette recette est verrouillée", yo: "Àwọn èròjà yìí ti pa" },
  "Enter PIN to unlock": { bis: "Ibutang ang PIN aron maabli", tg: "Ilagay ang PIN para i-unlock", zh: "输入PIN解锁", ko: "PIN 입력하여 잠금해제", hi: "अनलॉक करने के लिए PIN दर्ज करें", vi: "Nhập PIN để mở khóa", tw: "輸入PIN碼解鎖", th: "ใส่ PIN เพื่อปลดล็อค", hk: "輸入PIN碼解鎖", sg: "Masukkan PIN untuk buka kunci", it: "Inserisci PIN per sbloccare", fr: "Entrez PIN pour déverrouiller", yo: "Te PIN láti ṣí padà" },
  "Unlock": { bis: "Ablihi", tg: "I-unlock", zh: "解锁", ko: "잠금해제", hi: "अनलॉक", vi: "Mở khóa", tw: "解鎖", th: "ปลดล็อค", hk: "解鎖", sg: "Buka kunci", it: "Sblocca", fr: "Déverrouiller", yo: "Ṣí padà" },
  "Read": { bis: "Basaha", tg: "Basahin", zh: "朗读", ko: "읽기", hi: "पढ़ें", vi: "Đọc", tw: "朗讀", th: "อ่าน", hk: "朗讀", sg: "Baca", it: "Leggi", fr: "Lire", yo: "Kà" },
  "Pause": { bis: "Hunong", tg: "Pause", zh: "暂停", ko: "일시정지", hi: "रोकें", vi: "Tạm dừng", tw: "暫停", th: "หยุดชั่วคราว", hk: "暫停", sg: "Jeda", it: "Pausa", fr: "Pause", yo: "Dá dúró" },
  "Restart": { bis: "Sugdi pag-usab", tg: "Magsimula muli", zh: "重新开始", ko: "재시작", hi: "पुनः आरंभ", vi: "Bắt đầu lại", tw: "重新開始", th: "เริ่มใหม่", hk: "重新開始", sg: "Mulakan semula", it: "Riavvia", fr: "Recommencer", yo: "Bẹ̀rẹ̀ sí i lẹ́ẹ̀kàn" },
  "in your book": { bis: "sa imong libro", tg: "sa iyong libro", zh: "在你的书中", ko: "책에", hi: "पुस्तक में", vi: "trong sách", tw: "在你的書中", th: "ในหนังสือ", hk: "在你的書中", sg: "dalam buku anda", it: "nel tuo libro", fr: "dans votre livre", yo: "nínú ìwé rẹ" },
  "Your cookbook is empty.": { bis: "Walay sulod ang imong libro.", tg: "Walang laman ang iyong libro.", zh: "你的食谱书是空的。", ko: "요리책이 비어있습니다.", hi: "आपकी रेसिपी किताब खाली है।", vi: "Sách nấu ăn của bạn trống.", tw: "你的食譜書是空的。", th: "หนังสือทำอาหารของคุณว่างเปล่า", hk: "你的食譜書是空的。", sg: "Buku masakan anda kosong.", it: "Il tuo libro di ricette è vuoto.", fr: "Votre livre de recettes est vide.", yo: "Ìwé àwọn èròjà rẹ kò ní nkan." },
  "Create your first recipe": { bis: "Paghimo og imong unang resipe", tg: "Gumawa ng iyong unang resipe", zh: "创建你的第一个食谱", ko: "첫 레시피 만들기", hi: "अपनी पहली रेसिपी बनाएं", vi: "Tạo công thức đầu tiên", tw: "建立你的第一個食譜", th: "สร้างสูตรแรกของคุณ", hk: "建立你的第一個食譜", sg: "Buat resipi pertama anda", it: "Crea la tua prima ricetta", fr: "Créez votre première recette", yo: "Ṣ'àwọn èròjà àkọ́kọ́ rẹ" },
  "Review the parsed recipe below, then click Save to Book.": {
    bis: "Susihon ang gi-parse nga resipe sa ubos, unya i-klik ang I-save sa Libro.",
    tg: "Suriin ang na-parse na resipe sa ibaba, pagkatapos i-click ang I-save sa Libro.",
    zh: "查看下方解析的食谱，然后点击保存到书。",
    ko: "아래 파싱된 레시피를 검토한 후 책에 저장을 클릭하세요.",
    hi: "नीचे पार्स की गई रेसिपी देखें, फिर पुस्तक में सहेजें पर क्लिक करें।",
    vi: "Xem công thức đã phân tích bên dưới, sau đó nhấn Lưu vào sách.",
    tw: "查看下方解析的食譜，然後點擊儲存到書。",
    th: "ตรวจสอบสูตรที่วิเคราะห์ด้านล่าง แล้วคลิกบันทึกลงหนังสือ",
    hk: "查看下方解析的食譜，然後點擊儲存到書。",
    sg: "Semak resipi yang dihuraikan di bawah, kemudian klik Simpan ke Buku.",
    it: "Rivedi la ricetta analizzata sotto, poi clicca Salva nel Libro.",
    fr: "Vérifiez la recette analysée ci-dessous, puis cliquez Sauvegarder dans le Livre.",
    yo: "Yíwò àwọn èròjà tí a yíwò ní ìsàlẹ̀, lẹ́yìn náà tẹ Pàṣẹ sínú Ìwé.",
  },
  "Paste any recipe text — or use voice input to dictate. The offline parser will extract the title, ingredients, steps, timers, and auto-map icons. No internet required.": {
    bis: "I-paste ang bisan unsang resipe text — o gamita ang voice input. Ang offline parser mokuha sa titulo, sangkap, mga lakang, timer, ug auto-map icons. Walay internet kinahanglan.",
    tg: "I-paste ang anumang resipe text — o gamitin ang voice input. Kukuhain ng offline parser ang pamagat, sangkap, mga hakbang, timer, at auto-map icons. Walang internet kailangan.",
    zh: "粘贴任何食谱文本——或使用语音输入。离线解析器将提取标题、食材、步骤、计时器，并自动映射图标。无需网络。",
    ko: "레시피 텍스트를 붙여넣거나 음성 입력을 사용하세요. 오프라인 파서가 제목, 재료, 단계, 타이머를 추출하고 아이콘을 자동 매핑합니다. 인터넷 불필요.",
    hi: "किसी भी रेसिपी टेक्स्ट को पेस्ट करें — या वॉइस इनपुट का उपयोग करें। ऑफलाइन पार्सर शीर्षक, सामग्री, चरण, टाइमर निकालेगा और आइकन मैप करेगा। इंटरनेट की आवश्यकता नहीं।",
    vi: "Dán bất kỳ văn bản công thức — hoặc dùng nhập bằng giọng nói. Trình phân tích offline sẽ trích xuất tên, nguyên liệu, bước, hẹn giờ, và tự động gán biểu tượng. Không cần mạng.",
    tw: "貼上任何食譜文字——或使用語音輸入。離線解析器將提取標題、食材、步驟、計時器，並自動映射圖示。無需網路。",
    th: "วางข้อความสูตรใดก็ได้ — หรือใช้การป้อนเสียง ตัววิเคราะห์ออฟไลน์จะดึงชื่อ วัตถุดิบ ขั้นตอน ตัวจับเวลา และแมปไอคอนอัตโนมัติ ไม่ต้องใช้อินเทอร์เน็ต",
    hk: "貼上任何食譜文字——或使用語音輸入。離線解析器將提取標題、食材、步驟、計時器，並自動映射圖示。無需網路。",
    sg: "Tampal sebarang teks resipi — atau guna input suara. Penghurai luar talian akan mengekstrak tajuk, bahan, langkah, pemasa, dan pemetaan ikon automatik. Tidak perlu internet.",
    it: "Incolla qualsiasi testo di ricetta — o usa l'input vocale. Il parser offline estrarrà titolo, ingredienti, passi, timer e mappatura automatica delle icone. Nessuna connessione richiesta.",
    fr: "Collez n'importe quel texte de recette — ou utilisez la saisie vocale. L'analyseur hors ligne extraira le titre, les ingrédients, les étapes, les minuteurs et mappera les icônes. Aucune connexion requise.",
    yo: "Ẹ́kọ́ ẹ̀rọ̀ àwọn èròjà kankan — tàbí lo ìgboyà ohùn. Aláyèwò yóò yọ oríkì, èròjà, ìgbésẹ̀, àkókò, àti yí àwòrán padà. Kò ní fún ìdàkẹ̀mí.",
  },
  "Pro-Tip / Avoid (optional)": {
    bis: "Pro-Tip / Likayi (opsyonal)", tg: "Pro-Tip / Iwasan (opsyonal)",
    zh: "专业提示/避免（可选）", ko: "프로 팁/주의사항 (선택)", hi: "प्रो टिप/बचें (वैकल्पिक)",
    vi: "Mẹo/Tránh (tùy chọn)", tw: "專業提示/避免（選填）", th: "เคล็ดลับ/หลีกเลี่ยง (ไม่บังคับ)",
    hk: "專業提示/避免（選填）", sg: "Tip Pro/Elangkan (pilihan)", it: "Suggerimento Pro/Evitare (opzionale)",
    fr: "Astuce Pro/Éviter (optionnel)", yo: "Ìmọ̀ràn/Yíyọ (ìyàn)",
  },
  "Heat:": { bis: "Kainit:", tg: "Apoy:", zh: "火候:", ko: "불:", hi: "आंच:", vi: "Lửa:", tw: "火候:", th: "ไฟ:", hk: "火候:", sg: "Api:", it: "Fuoco:", fr: "Chaleur:", yo: "Iná:" },
  "Timer:": { bis: "Timer:", tg: "Timer:", zh: "计时器:", ko: "타이머:", hi: "टाइमर:", vi: "Hẹn giờ:", tw: "計時器:", th: "ตัวจับเวลา:", hk: "計時器:", sg: "Pemasa:", it: "Timer:", fr: "Minuteur:", yo: "Àkókò:" },
  "Ingredients in this step:": {
    bis: "Sangkap sa niining lakanga:", tg: "Sangkap sa hakbang na ito:",
    zh: "此步骤的食材:", ko: "이 단계의 재료:", hi: "इस चरण के सामग्री:", vi: "Nguyên liệu trong bước này:",
    tw: "此步驟的食材:", th: "วัตถุดิบในขั้นตอนนี้:", hk: "此步驟的食材:", sg: "Bahan dalam langkah ini:",
    it: "Ingredienti in questo passo:", fr: "Ingrédients dans cette étape:", yo: "Èròjà nínú ìgbésẹ̀ yìí:",
  },
  "Step": { bis: "Lakang", tg: "Hakbang", zh: "步骤", ko: "단계", hi: "चरण", vi: "Bước", tw: "步驟", th: "ขั้นตอน", hk: "步驟", sg: "Langkah", it: "Passo", fr: "Étape", yo: "Ìgbésẹ̀" },
  "of": { bis: "sa", tg: "ng", zh: "共", ko: "중", hi: "में से", vi: "trên", tw: "共", th: "จาก", hk: "共", sg: "dari", it: "di", fr: "sur", yo: "lára" },
  "Total:": { bis: "Tibook:", tg: "Kabuuan:", zh: "总计:", ko: "총:", hi: "कुल:", vi: "Tổng:", tw: "總計:", th: "รวม:", hk: "總計:", sg: "Jumlah:", it: "Totale:", fr: "Total:", yo: "Kíkún:" },
  "Wrong PIN": { bis: "Mali nga PIN", tg: "Maling PIN", zh: "PIN错误", ko: "PIN 오류", hi: "गलत PIN", vi: "Sai PIN", tw: "PIN碼錯誤", th: "PIN ผิด", hk: "PIN碼錯誤", sg: "PIN salah", it: "PIN errato", fr: "PIN incorrect", yo: "PIN àìtọ́" },
  "PINs do not match": { bis: "Di-match ang PIN", tg: "Hindi tugma ang PIN", zh: "PIN不匹配", ko: "PIN 불일치", hi: "PIN मेल नहीं खाता", vi: "PIN không khớp", tw: "PIN碼不匹配", th: "PIN ไม่ตรงกัน", hk: "PIN碼不匹配", sg: "PIN tidak sepadan", it: "PIN non corrispondono", fr: "PIN ne correspondent pas", yo: "PIN kò bára mu" },
  "PIN must be 4 digits": { bis: "Kinahanglan 4 ka digit ang PIN", tg: "Dapat 4 na numero ang PIN", zh: "PIN必须是4位数字", ko: "PIN은 4자리여야 합니다", hi: "PIN 4 अंकों का होना चाहिए", vi: "PIN phải có 4 số", tw: "PIN碼必須是4位數", th: "PIN ต้องเป็น 4 หลัก", hk: "PIN碼必須是4位數", sg: "PIN mesti 4 digit", it: "Il PIN deve essere di 4 cifre", fr: "Le PIN doit avoir 4 chiffres", yo: "PIN gbọdọ jẹ́ nọmbà mẹrin" },

  // Execution view
  "Step Text": { bis: "Lakang nga Teksto", tg: "Teksto ng Hakbang", zh: "步骤说明", ko: "단계 설명", hi: "चरण पाठ", vi: "Văn bản bước", tw: "步驟文字", th: "ข้อความขั้นตอน", hk: "步驟文字", sg: "Teks Langkah", it: "Testo Passo", fr: "Texte Étape", yo: "Ẹ̀kọ́ Ìgbésẹ̀" },

  // Recipe list meta
  "recipe": { bis: "resipe", tg: "resipe", zh: "食谱", ko: "레시피", hi: "रेसिपी", vi: "công thức", tw: "食譜", th: "สูตร", hk: "食譜", sg: "resipi", it: "ricetta", fr: "recette", yo: "àwọn èròjà" },
  "serving": { bis: "serbisyu", tg: "porsyon", zh: "份", ko: "인분", hi: "सर्विंग", vi: "phần", tw: "份", th: "ที่เสิร์ฟ", hk: "份", sg: "hidangan", it: "porzione", fr: "portion", yo: "ìpín" },
  "ingredient": { bis: "sangkap", tg: "sangkap", zh: "食材", ko: "재료", hi: "सामग्री", vi: "nguyên liệu", tw: "食材", th: "วัตถุดิบ", hk: "食材", sg: "bahan", it: "ingrediente", fr: "ingrédient", yo: "èròjà" },
};
